version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5436:5432
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run dev

volumes:
  db:
